# Generated by Django 4.2.7 on 2023-11-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_delete_cuenta_delete_tipo_cuenta'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Tipo_Cliente',
        ),
    ]
